### ISSUE TITLE
Prepare for Magento 2.4

### ISSUE THREAD

**Issue by katenorquay** [AddressFinder/addressfinder-magento#70]
- Drop support for Magento 2.1 and 2.2 going forward
- Update PHP version

**Comment by 1mattramsay** [comment]
Still waiting...

![image](https://user-images.githubusercontent.com/23350144/102563794-f8a0d600-413e-11eb-9f6d-0ca7c0766f4a.png)

**Comment by 1mattramsay** [comment]
Resolved and updated
