### ISSUE TITLE
Widget does not appear to be loading. Magneto Version 2.4

### ISSUE THREAD

**Issue by 1mattramsay** [AddressFinder/addressfinder-magento#84]
In formation about the customer [here](https://docs.google.com/document/d/19__IAPpQvZA2-NCwOk5gjx0hNr6vnFb8QmWRG92StFY/edit?usp=sharing)
Version: 2.4
There are a number of errors occurring on the page. Not sure if these are related to the issue or not.

Investigation required.

**Comment by dbashyal** [comment]
I'm having same issue. Addressfinder's address suggestion is not loading in 2.4.6-P6 shipping section. No issues in P5 though. Only difference is we had to enable CSP in P6 as required by the PayPal module.
