### ISSUE TITLE
Compatibility with Adobe Commerce 2.4.4

### ISSUE THREAD

**Issue by Andrewb89** [AddressFinder/addressfinder-magento#87]
Trying to install the extension via composer with Adobe Commerce 2.4.4 and not able to download the package because of composer dependency on PHP version below 8. Using PHP8.1. 

Do you have plans to update the extension?

**Comment by zakisaad** [comment]
Seconding this - we are planning a 2.3.x to 2.4.x upgrade and need 8.x PHP support.

**Comment by 1mattramsay** [comment]
Added support for PHP 8.0 and 8.1 on 9th May. Thanks for letting us know.
